# settings.py

SAVINGS_ACCOUNT_PROBABILITY = 0.35
SIMULATION_START_DATE = "2021-06-01"

DEFAULT_GRACE_DAYS = 30
DAY_SPAN = 7

DAILY_TRANSACTION_PROB = 0.05
CREDIT_APPLICATION_PROB = 0.10
LOAN_APPROVAL_PROB = 0.75  # Prawdopodobieństwo zaakceptowania wniosku
LOAN_PAYMENT_MAX_PROB = 0.015 * DAY_SPAN  # tuż przed terminem
LOAN_PAYMENT_MIN_PROB = 0.010 * DAY_SPAN # daleko od terminu

N_CUSTOMERS = 100


